### ISSUE TITLE
Problem about the t-SNE

### ISSUE THREAD

**Issue by DanJun6737** [tim-learn/NOUN#1]
您好，非常棒的工作，谢谢您的开源分享！
我在尝试复现您的工作，但是t-SNE出来的效果不太理想。
请问在A-->D这个任务上，您t-SNE可视化时选取的源域和目标域的样本分别是多少呢？
我两个域都选取的是480个样本，但出来的图效果不好。
同时对您绘图的色调十分感兴趣，如果可以的话能否分享一下t-SNE的代码呢？

期待您的回复！谢谢！

**Comment by tim-learn** [comment]
> 您好，非常棒的工作，谢谢您的开源分享！ 我在尝试复现您的工作，但是t-SNE出来的效果不太理想。 请问在A-->D这个任务上，您t-SNE可视化时选取的源域和目标域的样本分别是多少呢？ 我两个域都选取的是480个样本，但出来的图效果不好。 同时对您绘图的色调十分感兴趣，如果可以的话能否分享一下t-SNE的代码呢？
> 
> 期待您的回复！谢谢！

我们是两个数据域全部样本都使用了，直接使用t-sne降维绘制即可。
